### PR TITLE
Added instructions for PyCharm

### PR DESCRIPTION
**Pull request by ethanejohnsons**
This is a super basic set of instructions that should help others get this project up and running in PyCharm! Let me know if you know of a better way to do it, this is just what I ended up doing in my case.

### CODE REVIEW

**Comment by thecesrom** [comment]
Thanks, @ethanejohnsons.

I learned something new! I was not aware one could add the `src` as an additional path to the selected Python Interpreter.

But that effectively changes the `Ignition` dependency at the Interpreter level and affects all projects using that Interpreter.

There is another way to accomplish this, which is a bit easier, and it is "attaching" the `Ignition` project whether the user downloaded a version in particular from the releases or cloned it somewhere on their PC.

See: [Open, reopen, and close projects > Open multiple projects](https://www.jetbrains.com/help/pycharm/open-projects.html#f848e984)

This other method gives the users the ability to test-drive a newer version on a per-project basis, rather than at the Interpreter level.

What do you think?

**Comment by ethanejohnsons** [comment]
I see, that does seem to be a better way. Though, I did find I had to attach the `src/` directory specifically instead of the root `Ignition` directory if I didn't want to use `from src import system` or `src.system`, for example. Don't know how much that matters, or if there is a way around it that I'm not seeing.

**Comment by thecesrom** [comment]
> Don't know how much that matters, or if there is a way around it that I'm not seeing.

Yes, there is another way.

You may import `Ignition` and mark the `src` folder as `Sources Root`. See [here](https://www.jetbrains.com/help/pycharm/configuring-project-structure.html).

It may all be a matter of preference, but that's what I do, and I can do `import system.gui`, for example.

**Comment by ethanejohnsons** [comment]
I've updated the README again, is there anything else I should change?

**Comment by thecesrom** [comment]
Looks good!

**Pull request merged**
